In [1]:
import numpy as np

matrix = np.random.randint(0, 101, (5, 5))
mean_val = np.mean(matrix)
std_val = np.std(matrix)
var_val = np.var(matrix)
max_val = np.max(matrix)
min_val = np.min(matrix)
diag_sum = np.trace(matrix)
print("Matrix:\n", matrix)
print("Mean:", mean_val)
print("Std:", std_val)
print("Var:", var_val)
print("Max:", max_val)
print("Min:", min_val)
print("Diag Sum:", diag_sum)


Matrix:
 [[ 91  27  46  34  31]
 [ 26  27  14  65  67]
 [ 40  73  84  90  17]
 [  5  21  84  53  74]
 [100  40  37  94  60]]
Mean: 52.0
Std: 27.95997138768207
Var: 781.76
Max: 100
Min: 5
Diag Sum: 315


In [3]:
import numpy as np
scores = np.random.normal(50, 15, 1000)
scores = np.clip(scores, 0, 100)
mean_score = np.mean(scores)
median_score = np.median(scores)
std_score = np.std(scores)
below_50 = np.sum(scores < 50)

print("\nMean Score:", mean_score)
print("Median Score:", median_score)
print("Std Score:", std_score)
print("Below 50:", below_50)



Mean Score: 48.89374095488255
Median Score: 49.20077098829035
Std Score: 14.66058717841289
Below 50: 520


In [4]:
import pandas as pd

data = {
    "Student": ["Ali", "Ayşe", "Mehmet", "Zeynep", "Ahmet"],
    "Age": [20, 21, 19, 22, 20],
    "Department": ["Computer", "Physics", "Chemistry", "Computer", "Physics"],
    "Math": [70, 60, 80, 90, 55],
    "Physics": [65, 75, 70, 85, 60],
    "Chemistry": [80, 85, 65, 95, 70]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df, "\n")

avg_scores = df[["Math", "Physics", "Chemistry"]].mean()
print("Average Scores:\n", avg_scores, "\n")

max_math_student = df.loc[df["Math"].idxmax()]
print("Highest Math Student:\n", max_math_student, "\n")

df["Average"] = df[["Math", "Physics", "Chemistry"]].mean(axis=1)
print("DataFrame with Average:\n", df, "\n")

dept_avg = df.groupby("Department")[["Math", "Physics", "Chemistry", "Average"]].mean()
print("Department Averages:\n", dept_avg, "\n")

above_70 = df[df["Average"] > 70]
print("Students with Average > 70:\n", above_70)


DataFrame:
   Student  Age Department  Math  Physics  Chemistry
0     Ali   20   Computer    70       65         80
1    Ayşe   21    Physics    60       75         85
2  Mehmet   19  Chemistry    80       70         65
3  Zeynep   22   Computer    90       85         95
4   Ahmet   20    Physics    55       60         70 

Average Scores:
 Math         71.0
Physics      71.0
Chemistry    79.0
dtype: float64 

Highest Math Student:
 Student         Zeynep
Age                 22
Department    Computer
Math                90
Physics             85
Chemistry           95
Name: 3, dtype: object 

DataFrame with Average:
   Student  Age Department  Math  Physics  Chemistry    Average
0     Ali   20   Computer    70       65         80  71.666667
1    Ayşe   21    Physics    60       75         85  73.333333
2  Mehmet   19  Chemistry    80       70         65  71.666667
3  Zeynep   22   Computer    90       85         95  90.000000
4   Ahmet   20    Physics    55       60         70  61.6666