In [8]:
notes = [85, 92, 76, 92, 100, 76, 85, 92]
notes2 = set(notes)
max = 0
for note in notes:
    if max < note:
        max = note
print(max)
print(notes2)
notes.sort()
print(notes)

100
{100, 92, 85, 76}
[76, 76, 85, 85, 92, 92, 92, 100]


In [9]:
    number = int(input("enter a number"))
    digits = str(number)
    total = 0
    for d in digits:
        total += int(d) ** 3
    if total == number:
        print("armstrong")
    else:
        print("no armstrong") 


enter a number 12


no armstrong


In [10]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

common = A & B
print(common)

only_in_A = A - B
print(only_in_A)

union_sorted = sorted(A | B)
print(union_sorted)


{'Python', 'SQL'}
{'R', 'Java'}
['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [11]:
import random
import statistics

numbers = [random.randint(1, 100) for _ in range(10)]

mean_value = statistics.mean(numbers)
stdev_value = statistics.stdev(numbers)

print("Numbers:", numbers)
print("Mean:", mean_value)
print("Standard Deviation:", stdev_value)


Numbers: [71, 1, 33, 38, 72, 68, 54, 71, 72, 35]
Mean: 51.5
Standard Deviation: 24.098178815466994


In [1]:
numbers = [5, 12, 7, 18, 24, 3, 16]

even_numbers = filter(lambda x: x % 2 == 0, numbers)
squares = map(lambda x: x**2, even_numbers)
sorted_squares = sorted(squares, reverse=True)

print(list(sorted_squares))


[576, 324, 256, 144]


In [2]:
words = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sorted_words = sorted(words, key=lambda x: len(x))

print(sorted_words)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [3]:
def sum_of_numbers(s):
    import re
    numbers = re.findall(r'\d+', s)
    numbers = map(int, numbers)
    return sum(numbers)

text = "abc12def3"
print(sum_of_numbers(text))


15


In [4]:
import numpy as np

arr = np.random.randint(0, 51, size=10)
mean = np.mean(arr)
std = np.std(arr)
max_value = np.max(arr)

print("Array:", arr)
print("Mean:", mean)
print("Standard deviation:", std)
print("Max value:", max_value)


Array: [48 42 30  8  8 45  4 33  6 16]
Mean: 24.0
Standard deviation: 16.607227342335023
Max value: 48


In [5]:
import numpy as np

matrix = np.random.rand(5, 5)
column_means = np.mean(matrix, axis=0)
binary_matrix = (matrix > 0.5).astype(int)

print("Matrix:\n", matrix)
print("Column means:", column_means)
print("Binary matrix:\n", binary_matrix)


Matrix:
 [[0.00912192 0.88111225 0.11940967 0.43739998 0.38180321]
 [0.27489452 0.29645185 0.08214095 0.28025032 0.08135539]
 [0.59395636 0.76957184 0.79291149 0.42412083 0.59381337]
 [0.52683875 0.39584626 0.17632753 0.5968066  0.48673586]
 [0.31487141 0.32119018 0.70071332 0.34563286 0.39461722]]
Column means: [0.34393659 0.53283448 0.37430059 0.41684212 0.38766501]
Binary matrix:
 [[0 1 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [1 0 0 1 0]
 [0 0 1 0 0]]


In [6]:
import statistics

kitaplar = [
    {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
    {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
    {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
    {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
    {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
    {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
    {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

def top_selling_book(books):
    return max(books, key=lambda x: x['satis'])

def author_sales(books):
    sales = {}
    for book in books:
        sales[book['yazar']] = sales.get(book['yazar'], 0) + book['satis']
    return sales

all_types = set(book['tur'] for book in kitaplar)
high_sales_books = [book['isim'] for book in kitaplar if book['satis'] > 1000]

books_after_2020 = list(filter(lambda x: x['yil'] > 2020, kitaplar))
increased_sales = list(map(lambda x: int(x['satis'] * 1.1), kitaplar))
sorted_books = sorted(kitaplar, key=lambda x: x['satis'], reverse=True)

sales_list = [book['satis'] for book in kitaplar]
average_sales = statistics.mean(sales_list)
sales_std = statistics.stdev(sales_list)

from collections import Counter
types = [book['tur'] for book in kitaplar]
most_selling_type = Counter(types).most_common(1)[0][0]

print("Top selling book:", top_selling_book(kitaplar))
print("Author sales:", author_sales(kitaplar))
print("All types:", all_types)
print("High sales books:", high_sales_books)
print("Books after 2020:", books_after_2020)
print("Increased sales list:", increased_sales)
print("Books sorted by sales:", sorted_books)
print("Average sales:", average_sales)
print("Most selling type:", most_selling_type)
print("Sales standard deviation:", sales_std)


Top selling book: {'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}
Author sales: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}
All types: {'Sosyal', 'Sanat', 'Bilim', 'Akademik'}
High sales books: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
Books after 2020: [{'isim': 'Veri Bilimi 101', 'yazar': 'Ali', 'tur': 'Bilim', 'satis': 1200, 'yil': 2021}, {'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Matematiksel Modelleme', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 1500, 'yil': 2021}, {'isim': 'Bilgi Toplumu', 'yazar': 'Ayşe', 'tur': 'Sosyal', 'satis': 600, 'yil': 2022}]
Increased sales list: [1320, 1045, 770, 1980, 440, 1650, 660]
Books sorted by sales: [{'isim': 'Makine Öğrenmesi', 'yazar': 'Can', 'tur': 'Bilim', 'satis': 1800, 'yil': 2022}, {'isim': 'Matematiksel Modelleme', 'yazar': 'Ali', 'tur': 'Akademik', 'satis': 1500, 'yil': 2021}, {'isim': 'Veri Bilimi 101', 